Please look at API_ru
amperka/RGBEncoder pull request #1
Opened 2020-09-30 13:07 UTC by yurybotov

Обсуждения к API_ru можно вести по-русски :)

2020-09-30 16:46 UTC, yurybotov commented
Как вы думаете, int32_t - не перебор? Может ограничиться int16_t?

2020-10-01 08:03 UTC, igor605ds reviewed
Внёс свои пожелания)

2020-10-01 08:03 UTC, nomad605dis commented on API_ru.md
> +Изменяет адрес устройства на шине i2c и рестартует устройство с новым адресом.
RGBEncoder основан на всё том же модуле GPIOExpander, который в Octoliner:
https://github.com/amperka/Octoliner

Предлагаю делать аналогично функции, которые общие.
Т.е. нужно отдельная функция которая сохраняет адрес устройства.

2020-10-01 08:03 UTC, nomad605dis commented on API_ru.md
> +
RGBEncoder основан на всё том же модуле GPIOExpander, который в Octoliner:
https://github.com/amperka/Octoliner

Предлагаю делать аналогично функции, которые общие.
Т.е. тут добавить выбор шины Wire.

2020-10-01 08:03 UTC, nomad605dis commented on API_ru.md
> +
Может диапазон должен иметь отрицательные значения:
[-255;255]

2020-10-01 08:03 UTC, nomad605dis commented on API_ru.md
> +- `value`: устанавливаемое значение энкодера.
Я думаю надо указать минимальный и максимальный диапазон.

2020-10-01 08:03 UTC, igor605ds commented on API_ru.md
> +
Опять же указать диапазон. Предлагаю использовать отрицательную шкалу тоже.

2020-10-01 08:03 UTC, igor605ds commented on API_ru.md
> +
Предлагаю явно отразить какие методы потом можно использовать:

- onButton()
- onEncoder()

2020-10-01 08:45 UTC, AlexErAmp requested changes

2020-10-01 08:45 UTC, AlexErAmp commented on .clang-format
> +Language: Cpp
Думаю стоит убрать .clang-format в .gitignore. Зачем он нужен пользователю?

2020-10-01 08:45 UTC, AlexErAmp commented on API_ru.md
> +Изменяет адрес устройства на шине i2c и рестартует устройство с новым адресом.
"Рестартует" – не по-русски немного)

2020-10-01 08:45 UTC, AlexErAmp commented on API_ru.md
> +Реристрирует функцию - обработчик событий от энкодера
```suggestion
Регистрирует функцию-обработчик событий от энкодера.
```

2020-10-01 08:45 UTC, AlexErAmp commented on API_ru.md
> +Интерфейс прямого доступа:
```suggestion
- Интерфейс прямого доступа:
```

2020-10-01 08:45 UTC, AlexErAmp commented on API_ru.md
> +Псевдо-асинхронный интерфейс:
```suggestion
- Псевдо-асинхронный интерфейс:
```

2020-10-01 09:08 UTC, S-VIN commented
Мне хотелось бы ещё один режим работы с энкодером -- псевдо-асинхронный. Этот энкодер в этом режиме говорит, что энкодер повернули вправо или влево без координат.

Это позволит использовать его, когда не нужно знать точные координаты. Например, где энкодер управляет шагами шагового двигателя. Нам не нужно знать, какие координаты у энкодера, так как мы смотрим на двигатель. Разумеется, пользователь может в коде отслеживать по координатам, но так мы добавляем ему работу.

2020-10-01 09:12 UTC, yurybotov commented on API_ru.md
> +
В том-то и идея задания границ диапазона чтобы диапазон сделать произвольным. Для какого-то меню вполне хватит диапазона [0-2], для управления громкостью [0-1024] причем шаг 4, а тому кто делает генератор звуковых частот потребуется диапазон [1-33000], для какого нибудь холодильника диапазон может быть [-10...5].
Диапазон указанный в begin - диапазон по-умолчанию. Я подумал, что в среднестатистческих ардуино приложениях диапазон 0-255 применяется наиболее часто и задал его.

2020-10-01 09:13 UTC, yurybotov commented on API_ru.md
> +- `value`: устанавливаемое значение энкодера.
У нас нет информации гакие границы диапазона задаст пользователь.

2020-10-01 09:17 UTC, yurybotov commented on API_ru.md
> +
Отрицательная шкала разумеется есть, максимальный диапазон сейчас [MIN_LONG;MAX_LONG]. Я честно говоря подумываю не заменить ли long на short. Но пока long.

2020-10-01 09:20 UTC, yurybotov commented on API_ru.md
> +
Игорь этот метод нужен для всех. Для не-асинхронных тоже. Например в нем отрабатывается подавление дребезга кнопки, а RAW значения энкодера пересчитываются в заданныйпользователем диапазон.

2020-10-01 09:34 UTC, yurybotov commented
**S-VIN** Вообще этот режим легко сделать в существующем API:
_void handler(int32_t dir) {
 if(dir) { вправо } else { влево } 
}
setRange(0,1);
setMode(INBOUND);
onEncoder(handler);_
Но могу и отдельно сделать если это действительно нужно...

2020-10-01 09:50 UTC, yurybotov commented on API_ru.md
> +Интерфейс прямого доступа:
ок

2020-10-01 09:51 UTC, yurybotov commented on API_ru.md
> +Реристрирует функцию - обработчик событий от энкодера
ок

2020-10-01 10:02 UTC, yurybotov commented on .clang-format
> +Language: Cpp
Но он пользователю и не мешает. Тут скорее "обычай" - в других либах мы добавляли его. К тому-же будет сложнее придерживаться одинакового форматирования работая из разных мест с разных компьютеров. Я например дома работаю то в linux то в  винде, плюс рабочий компьютер.

2020-10-01 10:04 UTC, yurybotov commented on API_ru.md
> +
Принято. (На самом деле в библиотеке которую потихоньку клепаю уже добавил).

2020-10-01 10:11 UTC, nkrkv requested changes

2020-10-01 10:11 UTC, nkrkv commented on .clang-format
> +Language: Cpp
Пользователь в общем случае вообще сюда не полезет, а хранить настройки линтера вместе с исходниками — хороший тон. Пусть будет

2020-10-01 10:11 UTC, nkrkv commented on API_ru.md
> +- `mode`: устанавливаемый режим работы энкодера, может принимать значения INBOUND или CYCLIC.
```suggestion
- `mode`: устанавливаемый режим работы энкодера, может принимать значения `RGBENC_CLAMP` или `RGBENC_WRAP`. 
```

Добавил неймспейс, предлагаю изменение терминологии.

2020-10-01 10:11 UTC, nkrkv commented on API_ru.md
> +**Для кнопки и энкодера имеется два интерфейса: прямой доступ и псевдо-асинхронный.**
Симуляция заголовка жирным шрифтом. Заголовок должен быть заголовком… но в данном случае он вовсе не нужен.

То, что режима два — нужно поднять на самый верх, в описание самого класса. А что и как использовать, должно быть в examples. Напоминаю, здесь мы делаем API Reference.

2020-10-01 10:11 UTC, nkrkv commented on API_ru.md
> +### `int32_t getEncoderValue()`
```suggestion
### `int32_t getEncoderValue() const`
```

2020-10-01 10:11 UTC, nkrkv commented on API_ru.md
> +### `bool getButtonState()`
```suggestion
### `bool isButtonDown() const`
```

Что такое state? Это нажата или отжата?

2020-10-01 10:21 UTC, yurybotov commented on API_ru.md
> +### `bool getButtonState()`
Мне кажется лучше isButtonPressed

2020-10-01 10:22 UTC, yurybotov commented on API_ru.md
> +### `int32_t getEncoderValue()`
ок

2020-10-01 10:23 UTC, yurybotov commented on API_ru.md
> +- `mode`: устанавливаемый режим работы энкодера, может принимать значения INBOUND или CYCLIC.
Согласен

2020-10-01 10:26 UTC, yurybotov commented on API_ru.md
> +**Для кнопки и энкодера имеется два интерфейса: прямой доступ и псевдо-асинхронный.**
Done

2020-10-01 10:36 UTC, yurybotov commented on API_ru.md
> +
Done

2020-10-01 10:36 UTC, yurybotov commented on API_ru.md
> +Изменяет адрес устройства на шине i2c и рестартует устройство с новым адресом.
Done

2020-10-01 10:38 UTC, yurybotov commented on API_ru.md
> +Изменяет адрес устройства на шине i2c и рестартует устройство с новым адресом.
Я разбил функцию на две как в Октолайнере. Так что этого уже нет.

2020-10-01 11:08 UTC, yurybotov commented on API_ru.md
> +- `value`: устанавливаемое значение энкодера.
Я указал диапазон и добавил комментарий по его выбору.

2020-10-01 11:08 UTC, yurybotov commented on API_ru.md
> +
Диапазон указал

2020-10-01 11:54 UTC, S-VIN commented
> **S-VIN** Вообще этот режим легко сделать в существующем API:
> _void handler(int32_t dir) {
>  if(dir) { вправо } else { влево } 
> }
> setRange(0,1);
> setMode(INBOUND);
> onEncoder(handler);_
> Но могу и отдельно сделать если это действительно нужно...

Если это не совсем очевидно, то использовать будут немногие. На мой взгляд, функция важная. Надо сделать её очевидной.

2020-10-01 12:03 UTC, yurybotov commented
Думаю просто надо сделать такой example в котором описать решение данной задачи. Это логичнее чем обвешивать объект дополнительными методами.

2020-10-01 12:26 UTC, nkrkv commented on API_ru.md
> +### `bool getButtonState()`
Можно и pressed, не так важно

2020-10-02 14:41 UTC, yurybotov commented
Подумав добавил обработчики по рекомендации Степана.

2020-10-02 14:43 UTC, nkrkv approved these changes
LGTM

2020-10-02 14:45 UTC, S-VIN approved these changes
LGTM

2020-10-02 15:15 UTC, AlexErAmp approved these changes
LGTM

2020-10-02 15:41 UTC, igor605ds approved these changes
Пару мелких предложений. 

А так всё огонь. Не буду задерживать)

2020-10-02 15:41 UTC, igor605ds commented on API_ru.md
> +
Да среднестатистический диапазон диапазон [0...255].

Но ручка потенциометра крутится влево и вправо. И тут на мой взгляд диапазон с отрицательной шкалой по умолчанию встаёт лучше: [-255...255]. Типа изначально 0, а там в минус или в плюс.

2020-10-02 15:41 UTC, igor605ds commented on API_ru.md
> +
Ухххх какие числа))Я бы конечно взял бы short c меньшим диапазоном.

2020-10-02 15:41 UTC, igor605ds commented on API_ru.md
> +
Ок, понял. У меня такой метод обычно read() называется просто.

2020-10-02 16:04 UTC, merged